In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.activations import linear, relu
from tensorflow.keras.layers import Dense, LeakyReLU
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report

In [5]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df_model = df.copy()
df_model.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
df_model["Churn"] = df_model["Churn"].map({"Yes":1, "No":0})
df_model.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [8]:
df_model.drop("customerID", axis = 1, inplace = True)
df_model.drop("tenure", axis = 1, inplace = True)
df_model.drop("MonthlyCharges", axis = 1, inplace = True)
df_model.drop("TotalCharges", axis = 1, inplace = True)

df_model.head()

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Churn
0,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,0
1,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,0
2,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,1
3,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),0
4,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,1

In [9]:
df_model = pd.get_dummies(df_model, drop_first = True)
df_model.head()

,SeniorCitizen,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,True,False
1,0,0,True,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,1,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,0,True,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,0,1,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [10]:
x = df_model.drop("Churn", axis = 1)
y = df_model["Churn"]

In [11]:
x_train, x_, y_train, y_ = train_test_split(x, y, test_size = 0.3, random_state = 1)
x_cv, x_test, y_cv, y_test = train_test_split(x_, y_, test_size = 0.5, random_state = 1)

In [12]:
linear_scaler = StandardScaler()
x_train_sc = linear_scaler.fit_transform(x_train)
x_cv_sc = linear_scaler.transform(x_cv)
x_test_sc = linear_scaler.transform(x_test)

x_train_sc

array([[-0.43979045,  0.99433652, -0.9528351 , ..., -0.53089667,
         1.40607722, -0.54625403],
       [-0.43979045, -1.00569573,  1.04949954, ..., -0.53089667,
         1.40607722, -0.54625403],
       [ 2.27381019,  0.99433652,  1.04949954, ..., -0.53089667,
         1.40607722, -0.54625403],
       ...,
       [-0.43979045,  0.99433652, -0.9528351 , ..., -0.53089667,
         1.40607722, -0.54625403],
       [-0.43979045,  0.99433652, -0.9528351 , ..., -0.53089667,
        -0.71119849,  1.8306501 ],
       [-0.43979045, -1.00569573,  1.04949954, ..., -0.53089667,
        -0.71119849, -0.54625403]], shape=(4930, 27))

In [15]:
def nn_models():
    tf.random.set_seed(42)

    model_1 = Sequential([
        
        Dense(16, activation= "relu", kernel_regularizer = tf.keras.regularizers.l2(0.005)),
        Dense(8, activation="relu", kernel_regularizer = tf.keras.regularizers.l2(0.005)),
        Dense(1, activation= "sigmoid",kernel_regularizer = tf.keras.regularizers.l2(0.005))
    ],name = 'model_1')

    return model_1

In [17]:
from sklearn.metrics import recall_score

nn_train_mse = []
nn_cv_mse = []
nn_cv_recall = []

model = nn_models()

model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
)
    
print(f"Training : {model.name}")
    
model.fit(
    x_train_sc, y_train,
    epochs=20,
    verbose=1
)
    
print("Done!\n")

# ---- MSE (your existing code) ----
y_hat = model.predict(x_train_sc)
nn_train_mse.append(mean_squared_error(y_train, y_hat) / 2)
print(y_hat)

y_hat = model.predict(x_cv_sc)
nn_cv_mse.append(mean_squared_error(y_cv, y_hat) / 2)

    # ---- NEW: Recall calculation ----
y_pred = (y_hat >= 0.5).astype(int)
recall = recall_score(y_cv, y_pred)
print(classification_report(y_cv, y_pred))
nn_cv_recall.append(recall)

print("Results:\n")
for i in range(len(nn_train_mse)):
    print(
        f"Model {i+1} : "
        f"Training MSE: {nn_train_mse[i]:.5f}, "
        f"CV MSE: {nn_cv_mse[i]:.5f}, "
        f"CV Recall (Churn=1): {nn_cv_recall[i]:.5f}"
    )

Training : model_1
Epoch 1/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.9211
Epoch 2/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6838
Epoch 3/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6064
Epoch 4/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5690
Epoch 5/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5455
Epoch 6/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5287
Epoch 7/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5158
Epoch 8/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5059
Epoch 9/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4982
Epoch 10/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4920
Epoch 11/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 0.4870
Epoch 12/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.4831
Epoch 13/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4796
Epoch 14/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4768
Epoch 15/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4746
Epoch 16/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4730
Epoch 17/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.4716
Epoch 18/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.4701
Epoch 19/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4692
Epoch 20/20
155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4683
Done!

155/155 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
[[0.1735006 ]
 [0.51879543]
 [0.6618732 ]
 ...
 [0.56678796]
 [0.30422905]
 [0.03159801]]
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
              precision    recall  f1-score   support

           0       0.85      0.88      0.87       805
           1       0.57      0.51      0.54       251

    accuracy                           0.79      1056
   macro avg       0.71      0.70      0.70      1056
weighted avg       0.79      0.79      0.79      1056

Results:

Model 1 : Training MSE: 0.07221, CV MSE: 0.06460, CV Recall (Churn=1): 0.51394

In [31]:
import joblib
joblib.dump(linear_scaler, "scalar_nn.joblib")

['scalar_nn.joblib']

In [1]:
!pip install tf2onnx onnxruntime

Collecting tf2onnx
  Using cached tf2onnx-1.17.0-py3-none-any.whl.metadata (27 kB)
Collecting onnxruntime
  Using cached onnxruntime-1.26.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: numpy>=1.23.5 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from tf2onnx) (2.3.5)
Collecting onnx>=1.14.0 (from tf2onnx)
  Using cached onnx-1.21.0-cp312-abi3-win_amd64.whl.metadata (8.7 kB)
Requirement already satisfied: requests in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from tf2onnx) (2.32.4)
Requirement already satisfied: flatbuffers>=1.12 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from tf2onnx) (25.12.19)
Requirement already satisfied: protobuf>=3.20 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from tf2onnx) (6.33.4)
Requirement already satisfied: packaging in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from onnxruntime) (25.0)
Requirement already satisfied: typing_extensions>=4.7.1 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from onnx>=1.14.0->tf2onnx) (4.15.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from onnx>=1.14.0->tf2onnx) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from requests->tf2onnx) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from requests->tf2onnx) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from requests->tf2onnx) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages (from requests->tf2onnx) (2025.7.14)
Using cached tf2onnx-1.17.0-py3-none-any.whl (839 kB)
Downloading onnxruntime-1.26.0-cp313-cp313-win_amd64.whl (13.0 MB)
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
    --------------------------------------- 0.3/13.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/13.0 MB 1.4 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/13.0 MB 1.4 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/13.0 MB 1.4 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/13.0 MB 1.4 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/13.0 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.4/13.0 MB 1.5 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/13.0 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/13.0 MB 1.6 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/13.0 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 3.9/13.0 MB 1.6 MB/s eta 0:00:06
   ------------ --------------------------- 4.2/13.0 MB 1.6 MB/s eta 0:00:06
   ------------- -------------------------- 4.5/13.0 MB 1.6 MB/s eta 0:00:06
   --------------- ------------------------ 5.0/13.0 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/13.0 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 5.5/13.0 MB 1.6 MB/s eta 0:00:05
   ----------------- ---------------------- 5.8/13.0 MB 1.6 MB/s eta 0:00:05
   ------------------- -------------------- 6.3/13.0 MB 1.6 MB/s eta 0:00:05
   -------------------- ------------------- 6.8/13.0 MB 1.7 MB/s eta 0:00:04
   --------------------- ------------------ 7.1/13.0 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 7.6/13.0 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 8.1/13.0 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 8.7/13.0 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 9.2/13.0 MB 1.8 MB/s eta 0:00:03
   ----------------------------- ---------- 9.7/13.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 10.0/13.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 10.2/13.0 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 10.2/13.0 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 10.5/13.0 MB 1.7 MB/s eta 0:00:02
   ---------------------------------- ----- 11.3/13.0 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/13.0 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/13.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  12.8/13.0 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 13.0/13.0 MB 1.8 MB/s  0:00:07
Downloading onnx-1.21.0-cp312-abi3-win_amd64.whl (16.4 MB)
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
    --------------------------------------- 0.3/16.4 MB ? eta -:--:--
    --------------------------------------- 0.3/16.4 MB ? eta -:--:--
    --------------------------------------- 0.3/16.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.4 MB 404.8 kB/s eta 0:00:40
   -- ------------------------------------- 1.0/16.4 MB 1.0 MB/s eta 0:00:16
   --- ------------------------------------ 1.6/16.4 MB 1.2 MB/s eta 0:00:13
   ----- ---------------------------------- 2.1/16.4 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.4/16.4 MB 1.5 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/16.4 MB 1.5 MB/s eta 0:00:09
   -------- ------------------------------- 3.4/16.4 MB 1.6 MB/s eta 0:00:09
   -------- ------------------------------- 3.7/16.4 MB 1.7 MB/s eta 0:00:08
   ---------- ----------------------------- 4.2/16.4 MB 1.7 MB/s eta 0:00:08
   ----------- ---------------------------- 4.7/16.4 MB 1.8 MB/s eta 0:00:07
   ------------ --------------------------- 5.0/16.4 MB 1.7 MB/s eta 0:00:07
   ------------ --------------------------- 5.2/16.4 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 5.8/16.4 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 6.0/16.4 MB 1.7 MB/s eta 0:00:07
   --------------- ------------------------ 6.3/16.4 MB 1.7 MB/s eta 0:00:06
   --------------- ------------------------ 6.6/16.4 MB 1.7 MB/s eta 0:00:06
   ---------------- ----------------------- 6.8/16.4 MB 1.7 MB/s eta 0:00:06
   ----------------- ---------------------- 7.1/16.4 MB 1.7 MB/s eta 0:00:06
   ------------------ --------------------- 7.6/16.4 MB 1.6 MB/s eta 0:00:06
   ------------------ --------------------- 7.6/16.4 MB 1.6 MB/s eta 0:00:06
   ------------------- -------------------- 7.9/16.4 MB 1.6 MB/s eta 0:00:06
   ------------------- -------------------- 7.9/16.4 MB 1.6 MB/s eta 0:00:06
   ------------------- -------------------- 8.1/16.4 MB 1.5 MB/s eta 0:00:06
   ------------------- -------------------- 8.1/16.4 MB 1.5 MB/s eta 0:00:06
   -------------------- ------------------- 8.4/16.4 MB 1.4 MB/s eta 0:00:06
   --------------------- ------------------ 8.7/16.4 MB 1.5 MB/s eta 0:00:06
   ---------------------- ----------------- 9.2/16.4 MB 1.5 MB/s eta 0:00:06
   ---------------------- ----------------- 9.4/16.4 MB 1.5 MB/s eta 0:00:05
   ----------------------- ---------------- 9.7/16.4 MB 1.5 MB/s eta 0:00:05
   ------------------------ --------------- 10.2/16.4 MB 1.5 MB/s eta 0:00:05
   ------------------------- -------------- 10.5/16.4 MB 1.5 MB/s eta 0:00:05
   -------------------------- ------------- 10.7/16.4 MB 1.5 MB/s eta 0:00:04
   -------------------------- ------------- 11.0/16.4 MB 1.5 MB/s eta 0:00:04
   -------------------------- ------------- 11.0/16.4 MB 1.5 MB/s eta 0:00:04
   --------------------------- ------------ 11.3/16.4 MB 1.4 MB/s eta 0:00:04
   ---------------------------- ----------- 11.8/16.4 MB 1.4 MB/s eta 0:00:04
   ---------------------------- ----------- 11.8/16.4 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 12.1/16.4 MB 1.4 MB/s eta 0:00:04
   ------------------------------ --------- 12.6/16.4 MB 1.4 MB/s eta 0:00:03
   ------------------------------- -------- 12.8/16.4 MB 1.4 MB/s eta 0:00:03
   ------------------------------- -------- 13.1/16.4 MB 1.4 MB/s eta 0:00:03
   --------------------------------- ------ 13.6/16.4 MB 1.4 MB/s eta 0:00:02
   --------------------------------- ------ 13.9/16.4 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 14.2/16.4 MB 1.4 MB/s eta 0:00:02
   ----------------------------------- ---- 14.7/16.4 MB 1.5 MB/s eta 0:00:02
   ------------------------------------ --- 15.2/16.4 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.4 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.4 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 16.4/16.4 MB 1.5 MB/s  0:00:11
Installing collected packages: onnxruntime, onnx, tf2onnx

   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ---------------------------------------- 0/3 [onnxruntime]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   ------------- -------------------------- 1/3 [onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   -------------------------- ------------- 2/3 [tf2onnx]
   ---------------------------------------- 3/3 [tf2onnx]

Successfully installed onnx-1.21.0 onnxruntime-1.26.0 tf2onnx-1.17.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
model.save('churn_nn_model.keras')

In [24]:
import tensorflow as tf
import tf2onnx
import onnx

# 1. Load the Keras model
keras_model = tf.keras.models.load_model('churn_nn_model.keras')

# 2. Define the inference function tracing back to Keras
@tf.function
def run_inference(tensor_input):
    return keras_model(tensor_input)

# 3. Pass the raw python function to tf2onnx (let it extract the graph automatically)
onnx_model, _ = tf2onnx.convert.from_function(
    run_inference, 
    input_signature=[tf.TensorSpec([None, 27], tf.float32, name="input")]
)

# 4. Save the optimized model graph
onnx.save(onnx_model, 'churn_nn_model.onnx')
print("✅ Success! 'churn_nn_model.onnx' has been generated cleanly.")

WARNING:tensorflow:From C:\Users\Lenovo\anaconda3\envs\pandas-playground\Lib\site-packages\tf2onnx\tf_loader.py:192: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From C:\Users\Lenovo\anaconda3\envs\pandas-playground\Lib\site-packages\tf2onnx\tf_loader.py:834: The name tf.train.export_meta_graph is deprecated. Please use tf.compat.v1.train.export_meta_graph instead.

✅ Success! 'churn_nn_model.onnx' has been generated cleanly.